version: "3.8"
services:
    db:
        image: postgres:14
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgrespw
            PGDATA: /var/lib/postgresql/data
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "5432:5432"
    service:
        image: pokemon_trading
        restart: always
        environment:
            HOST: 0.0.0.0
            PORT: 8080
            DATABASE_URL: postgres://postgres:postgrespw@pgsql-server:5432/pokemon
        ports:
            - "8080:8080"
        links:
            - "db:pgsql-server"
        depends_on:
            - db
volumes:
    db-data:
